export type ContentType = 'x_article' | 'external_article' | 'company_blog_article' | 'media_article' | 'vc_article' | 'research_blog_article';

export type SourcePlatform = 'x' | 'rss' | 'json_feed' | 'sitemap' | 'html_index' | 'manual' | 'hn' | 'external';
export type DiscoveryMethod = 'rss' | 'atom' | 'json_feed' | 'sitemap' | 'html_index' | 'manual' | 'curated_x' | 'curated_external';

export type Candidate = {
  id: string;
  canonical_url: string;
  source_url: string;
  source_platform: SourcePlatform;
  source_type: string;
  source_domain: string;
  content_type: ContentType;
  title: string;
  subtitle?: string;
  author?: string;
  author_handle?: string;
  author_role?: string;
  organization?: string;
  language?: string;
  published_at?: string;
  captured_at: string;
  discovery_run_date?: string;
  discovery_method?: DiscoveryMethod;
  live_fetch?: boolean;
  first_seen_key?: string;
  lastmod?: string;
  summary?: string;
  excerpt?: string;
  raw_text_available: boolean;
  topics: string[];
  tags: string[];
  entities: string[];
  mentioned_companies: string[];
  mentioned_people: string[];
  mentioned_products: string[];
  mentioned_papers: string[];
  mentioned_repos: string[];
  evidence_links: string[];
  engagement: Record<string, number | undefined>;
  source_score: number;
  information_density_score: number;
  originality_score: number;
  trend_score: number;
  evidence_score: number;
  heat_score: number;
  site_fit_score: number;
  total_score: number;
  rank?: number;
  cluster_id?: string;
  dedupe_key: string;
  title_hash: string;
  status: 'candidate' | 'selected' | 'archived' | 'rejected';
  reason_selected?: string;
  reason_rejected?: string;
  fetch_status: 'ok' | 'partial' | 'failed' | 'skipped';
  fetch_error?: string;
  first_seen_issue?: string;
  last_seen_issue?: string;
  used_in_issue?: string;
  core_takeaway?: string;
  why_it_matters?: string;
  possible_impact?: string;
  what_to_watch_next?: string;
};

export type Cluster = {
  cluster_id: string;
  title: string;
  summary: string;
  primary_source: string;
  supporting_sources: string[];
  related_x_posts: string[];
  related_articles: string[];
  entities: string[];
  tags: string[];
  score: number;
  selected_item_id: string;
};
